import Navbar from "@/components/Navbar";
import "@/globals.css";
import { Poppins } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: "Next.js, Tailwind CSS, PostCSS",
};

const poppins = Poppins({
  weight: ["300", "400", "500", "700"],
  styles: ["italic", "normal"],
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={poppins.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
